// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWreqt2et7exEf1oEqdGGGsBEWU2HLnlA',
    appId: '1:972428316223:web:fd953452121e6bd4ab728a',
    messagingSenderId: '972428316223',
    projectId: 'e-commerce-6c6cf',
    authDomain: 'e-commerce-6c6cf.firebaseapp.com',
    storageBucket: 'e-commerce-6c6cf.appspot.com',
    measurementId: 'G-07ZFHVKDL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcvgV4nfSlqOjCWk3-CFHSwEjlBhR35YI',
    appId: '1:972428316223:android:8fff1a4e29ee12caab728a',
    messagingSenderId: '972428316223',
    projectId: 'e-commerce-6c6cf',
    storageBucket: 'e-commerce-6c6cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5hqYqisCPQdw5FO9ZCIiX1L-pTb8R_sY',
    appId: '1:972428316223:ios:acdc245f05a4e4c8ab728a',
    messagingSenderId: '972428316223',
    projectId: 'e-commerce-6c6cf',
    storageBucket: 'e-commerce-6c6cf.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5hqYqisCPQdw5FO9ZCIiX1L-pTb8R_sY',
    appId: '1:972428316223:ios:acdc245f05a4e4c8ab728a',
    messagingSenderId: '972428316223',
    projectId: 'e-commerce-6c6cf',
    storageBucket: 'e-commerce-6c6cf.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWreqt2et7exEf1oEqdGGGsBEWU2HLnlA',
    appId: '1:972428316223:web:fe176dd7f49cb5a2ab728a',
    messagingSenderId: '972428316223',
    projectId: 'e-commerce-6c6cf',
    authDomain: 'e-commerce-6c6cf.firebaseapp.com',
    storageBucket: 'e-commerce-6c6cf.appspot.com',
    measurementId: 'G-QL6B39QV5R',
  );
}
